import bcrypt from "bcryptjs";

export const data = {
  users: [
    {
      name: "Josip",
      email: "mile1@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "mile1234@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Košulja",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 0,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes1",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes2",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 122,
      brand: "nike",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes3",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes 2",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike Košulja",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes1",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes2",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 122,
      brand: "nike",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes3",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes 3",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike Košulja",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes1",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes2",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 122,
      brand: "nike",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes3",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes 10",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike Košulja",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes1",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes2",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 122,
      brand: "nike",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes3",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes 100",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike Košulja",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes1",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes2",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 122,
      brand: "nike",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes3",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike Košulja",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes1",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes2",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 122,
      brand: "nike",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes3",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 0,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
    {
      name: "Nike shoes",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countInStock: 3,
      sizes: [
        {
          size: "xl",
          quantity: 2,
        },
        {
          size: "l",
          quantity: 3,
        },
      ],
    },
  ],
};
